spring:

  #MYSQL
  datasource-mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/local
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    custom-param:
      hibernate:
        ddl-auto: create-drop

  #POSTGRESQL
  datasource-postgresql:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=local
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    custom-param:
      hibernate:
        ddl-auto: create-drop

  jpa:
    show-sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true

